### ISSUE TITLE
Doesn't work in Godot 4 (rc1)

### ISSUE THREAD

**Issue by des1redState** [adamviola/simple-free-look-camera#4]
There's various reasons this code doesn't work in Godot 4, from renamed functions to the introduction of annotations, so it's probably quicker for a maintainer to just try to run it and watch the debugger output, but it'd be really great to have this working now we've reached the Godot 4 Release Candidate. Unfortunately I'm still somewhat of a noob otherwise I would have opened a PR.

**Comment by adamviola** [comment]
Updated! Thanks for the issue.
